#!/usr/bin/python3

states = [['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Alberta', 'AB'],
          ['American Samoa', 'AS'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['British Columbia', 'BC'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Guam', 'GU'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Manitoba', 'MB'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Brunswick', 'NB'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['Newfoundland and Labrador', 'NL'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Northern Mariana Islands', 'MP'],
          ['Northwest Territories', 'NT'],
          ['Nova Scotia', 'NS'],
          ['Nunavut', 'NU'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Online', 'Online'],
          ['Ontario', 'ON'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Prince Edward Island', 'PE'],
          ['Puerto Rico', 'PR'],
          ['Quebec', 'QC'],
          ['Rhode Island', 'RI'],
          ['Saskatchewan', 'SK'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['UK', 'UK'],
          ['US Virgin Islands', 'VI'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['Washington DC', 'DC'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY'],
          ['Yukon', 'YT'],
          ['other', 'other']]
